/**
 * SISA 5-tier user roles.
 *
 * @author GentleAI SISA Architecture Team
 */
export enum ScuRoleEnum {
  ROLE_DOCENTE = 'ROLE_DOCENTE',
  ROLE_DIR_CARRERA = 'ROLE_DIR_CARRERA',
  ROLE_DIR_ACADEMICA = 'ROLE_DIR_ACADEMICA',
  ROLE_VICERRECTOR_SEDE = 'ROLE_VICERRECTOR_SEDE',
  ROLE_VICERRECTOR_NACIONAL = 'ROLE_VICERRECTOR_NACIONAL'
}
